services:
  nginx-proxy:
    image: nginx:1.25.3-alpine
    container_name: nginx-reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx-static-content:/usr/share/nginx/html:ro
      - nginx_cache_data:/var/cache/nginx
    depends_on:
      - apache-backend
    restart: unless-stopped

  apache-backend:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: apache-backend-aula3
    ports:
      - "8081:80"
    volumes:
      - ./apache-backend/html:/var/www/html
      - ./apache-backend/logs:/var/log/apache2
    restart: unless-stopped


volumes:
  nginx_cache_data:
